version: "2"
services:

  redis:
    image: redis
    container_name: grace_redis
    restart: always
  
  postgres:
    image: postgres
    container_name: grace_postgres
    restart: always
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=grace
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
  
  django:
    build: ./project
    container_name: grace_django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./project:/project
    environment:
      - DEBUG=true
      - SECRET_KEY=d@nz3krc%97qc$$*&u6mgjl$$oi3whrjeg2b&a!xqq&=t!*)ge8_
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=grace
      - DB_USER=postgres
      - DB_PASS=password
    ports:
      - "8000:8000"
    depends_on:
      - postgres